version: '3'

services:
  mongo:
    image: mongo:7.0.1
    container_name: "mongo-container"
    #network_mode: host
    ports:
    - "27017:27017" # maps container port 27017 to host port 27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_DBNAME: a
    volumes:
      - './dockervolume/mongodb:/data/db'

# docker-compose -f docker-mongo.yml up -d