version: '3'
# todo better container names 
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2 
    container_name: logstash
    volumes:
      - ./logstash-config/:/usr/share/logstash/pipeline/  #todo gonna be configmap
    ports:
      - "5001:5001"
    networks:
      - elk-network
      - rabbitmq-network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elk-network
    depends_on:
      - elasticsearch

networks:
  elk-network:
    driver: bridge
  rabbitmq-network:
    driver: bridge  # docker handles this automatically
#    external:
#      name: rabbitmq-network # actual name of the external network created manually


# elasticsearch query
#GET /logstash-*/_search
#{
#  "query": {
#    "match_all": {}
#  }
#}

#GET /logstash-*/_search
#{
#  "query": {
#    "match": {
#      "loglevel": "error"
#    }
#  }
#}

# docker compose -f docker-ELK.yml up