version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    ports:
      - "5672:5672" # RabbitMQ AMQP port
      - "15672:15672" # RabbitMQ management console port
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: test
    volumes:
      - ./rabbitmq-data:/var/lib/rabbitmq # Persist RabbitMQ data
    networks:
      - rabbitmq-network

networks:
  rabbitmq-network:
    driver: bridge
    
# docker compose -f docker-rabbitmq.yml up



